language: php
sudo: false
cache: {directories: [$HOME/.composer]}
jobs:
  include:
    - &BASE
      php: 7.1
      install: [travis_retry make ci-install]
      script: [make ci-test || travis_terminate 1]

    - <<: *BASE
      php: 7.2

    - <<: *BASE
      after_success: [travis_retry make ci-coverage]
